name: Multibranch pipeline
run-name: 'Multibranch ${{ github.head_ref || github.ref_name }}'
on:
  push:
    branches:
      - main
      - release/*
      - feature/*
      - bugfix/*
  workflow_dispatch:
    inputs:
      skipSmokeTests:
        description: Should skip smoke tests?
        type: boolean
        required: false
        default: false
      hubEnv:
       description: Select target hub and stage
       required: true
       type: choice
       options:
        - BACKEND_EMEA_TEST
    
jobs:
  properties:
    uses: ./.github/workflows/datacenterMap.yml
    with:
      hubEnv: '${{ inputs.hubEnv }}'
    secrets: inherit

  buildTestDeploy:
    runs-on: ubuntu-latest
    needs: properties
    env:
      AWS_ACCOUNT: '${{ needs.properties.outputs.AWS_ACCOUNT }}'
      AWS_PROFILE: '${{ needs.properties.outputs.PROFILE }}'
      AWS_KEY: '${{ secrets[format(''{0}_AWS_KEY'', inputs.hubEnv)] }}'
      AWS_SECRET: '${{ secrets[format(''{0}_AWS_SECRET'', inputs.hubEnv)] }}'
      AWS_REGION: '${{ needs.properties.outputs.REGION }}'
      CLUSTER_NAME: '${{ needs.properties.outputs.CLUSTER_NAME }}'
      SERVICE_NAME: '${{ needs.properties.outputs.SERVICE_NAME }}'
      TASK_NAME: '${{ needs.properties.outputs.TASK_NAME }}'
    #    TODO Checkout, JDK 17 setup, Maven setup, Build with JaCoCo, Configure AWS credentials, Login to Amazon ECR, Push image to Amazon ECR, Deploy Amazon ECS task definition, Run smoke tests if not skipped


    steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            fetch-depth: 0

        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            distribution: 'corretto'
            java-version: '17'

        - name: "Set up docker"
          uses: "docker/setup-buildx-action@v2"

        - name: "Build & Test with JaCoCo"
          run: mvn clean verify

        - name: "Configure AWS credentials"
          run: >
            mkdir -p ~/.aws

            echo "[${{ env.AWS_PROFILE }}]" > ~/.aws/credentials

            echo "aws_access_key_id = ${{ env.AWS_KEY }}" >> ~/.aws/credentials

            echo "aws_secret_access_key = ${{ env.AWS_SECRET }}" >>
            ~/.aws/credentials

        - name: "Login to Amazon ECR"
          run: aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.AWS_ACCOUNT }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com

        - name: "Build the docker image"
          run: docker build -t ${{ env.SERVICE_NAME }} .

        - name: "Tag the docker image"
          run: docker tag ${{ env.SERVICE_NAME }}:latest ${{ env.AWS_ACCOUNT }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.SERVICE_NAME }}:latest

        - name: "Push the docker image to Amazon ECR"
          run: docker push ${{ env.AWS_ACCOUNT }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.SERVICE_NAME }}:latest

        - name: "Deploy Amazon ECS task definition"
          run: |
                aws ecs update-service --cluster ${{ env.CLUSTER_NAME }} --service ${{ env.SERVICE_NAME }} --force-new-deployment --region ${{ env.AWS_REGION }}

        - name: "Run smoke tests if not skipped"
          if: ${{ !inputs.skipSmokeTests }}
          run: |
            echo "Running smoke tests..."
            mvn -pl api-backend-v1-test test -Dtest=SmokeBackendTest



  pipelinePassed:
    runs-on: ubuntu-latest
    needs: buildTestDeploy
    steps:
      - name: All passed
        run: |
          echo "All steps have passed."
